// Code generated by mockery v2.42.1. DO NOT EDIT.

//go:build !compile

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockConnection is an autogenerated mock type for the Connection type
type MockConnection struct {
	mock.Mock
}

type MockConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnection) EXPECT() *MockConnection_Expecter {
	return &MockConnection_Expecter{mock: &_m.Mock}
}

// Context provides a mock function with given fields:
func (_m *MockConnection) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// MockConnection_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockConnection_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockConnection_Expecter) Context() *MockConnection_Context_Call {
	return &MockConnection_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockConnection_Context_Call) Run(run func()) *MockConnection_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnection_Context_Call) Return(_a0 context.Context) *MockConnection_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnection_Context_Call) RunAndReturn(run func() context.Context) *MockConnection_Context_Call {
	_c.Call.Return(run)
	return _c
}

// HandleRequests provides a mock function with given fields:
func (_m *MockConnection) HandleRequests() {
	_m.Called()
}

// MockConnection_HandleRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleRequests'
type MockConnection_HandleRequests_Call struct {
	*mock.Call
}

// HandleRequests is a helper method to define mock.On call
func (_e *MockConnection_Expecter) HandleRequests() *MockConnection_HandleRequests_Call {
	return &MockConnection_HandleRequests_Call{Call: _e.mock.On("HandleRequests")}
}

func (_c *MockConnection_HandleRequests_Call) Run(run func()) *MockConnection_HandleRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnection_HandleRequests_Call) Return() *MockConnection_HandleRequests_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnection_HandleRequests_Call) RunAndReturn(run func()) *MockConnection_HandleRequests_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with given fields:
func (_m *MockConnection) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockConnection_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockConnection_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockConnection_Expecter) ID() *MockConnection_ID_Call {
	return &MockConnection_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockConnection_ID_Call) Run(run func()) *MockConnection_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnection_ID_Call) Return(_a0 string) *MockConnection_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnection_ID_Call) RunAndReturn(run func() string) *MockConnection_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: msg
func (_m *MockConnection) Send(msg interface{}) error {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConnection_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockConnection_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - msg interface{}
func (_e *MockConnection_Expecter) Send(msg interface{}) *MockConnection_Send_Call {
	return &MockConnection_Send_Call{Call: _e.mock.On("Send", msg)}
}

func (_c *MockConnection_Send_Call) Run(run func(msg interface{})) *MockConnection_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockConnection_Send_Call) Return(_a0 error) *MockConnection_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnection_Send_Call) RunAndReturn(run func(interface{}) error) *MockConnection_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConnection creates a new instance of MockConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnection {
	mock := &MockConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
