// Code generated by mockery v2.42.1. DO NOT EDIT.

//go:build !compile

package mocks

import (
	wasabi "github.com/ksysoev/wasabi"
	mock "github.com/stretchr/testify/mock"
)

// MockBackend is an autogenerated mock type for the Backend type
type MockBackend struct {
	mock.Mock
}

type MockBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackend) EXPECT() *MockBackend_Expecter {
	return &MockBackend_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: conn, r
func (_m *MockBackend) Handle(conn wasabi.Connection, r wasabi.Request) error {
	ret := _m.Called(conn, r)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(wasabi.Connection, wasabi.Request) error); ok {
		r0 = rf(conn, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBackend_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockBackend_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - conn wasabi.Connection
//   - r wasabi.Request
func (_e *MockBackend_Expecter) Handle(conn interface{}, r interface{}) *MockBackend_Handle_Call {
	return &MockBackend_Handle_Call{Call: _e.mock.On("Handle", conn, r)}
}

func (_c *MockBackend_Handle_Call) Run(run func(conn wasabi.Connection, r wasabi.Request)) *MockBackend_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(wasabi.Connection), args[1].(wasabi.Request))
	})
	return _c
}

func (_c *MockBackend_Handle_Call) Return(_a0 error) *MockBackend_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBackend_Handle_Call) RunAndReturn(run func(wasabi.Connection, wasabi.Request) error) *MockBackend_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBackend creates a new instance of MockBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackend {
	mock := &MockBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
